### ISSUE TITLE
Missing notes from PyCon US 2024

### ISSUE THREAD

**Issue by shivaylamba** [psf/webassembly#6]
Are there any updates to these meetings - especially for WASI 2 support

**Comment by brettcannon** [comment]
There was a summit at PyCon US, but no one who attended as seemed to have added notes (maybe @ntoll can?).

As for WASI 0.2, it's on my TODO list to try and [get `wasm32-wasip2` working](https://github.com/python/cpython/issues/121634).

**Comment by shivaylamba** [comment]
Alright I am really looking forward to this!

**Comment by ntoll** [comment]
:wave: I was only able to attend the morning session of PyCon WASM summit, I can certainly add notes about what happened and so on. The afternoon was an un-conference-y "improvised" session facilitated by @fpliger. I was giving a workshop in the education summit during the course of that afternoon.

Adding notes about the EuroPython WASM summit are also incoming too. Apologies for the delay, this is mostly down to juggling the inevitable infinite to-do list of "stuff". :wink:

**Comment by ntoll** [comment]
All feedback on [the PR](https://github.com/psf/webassembly/pull/7) most welcome.

**Comment by rajsite** [comment]
Are there recordings of the presentations available?

**Comment by ntoll** [comment]
@rajsite apart from the referenced YouTube video of the pre-recorded MicroPython session with Damien and myself, alas no.
